feat: try to infer package name from path
pksunkara/cargo-workspaces pull request #140
Opened 2023-12-22 13:39 UTC by RobWalt

Tries to solve this comment

https://github.com/pksunkara/cargo-workspaces/issues/46#issuecomment-1229234635

The basic idea is to reduce friction in using this tool by making the "specify an alternative package name" opt-in via optional command line arguments instead of requiring it.

There are two scenarios now that are new from the UX perspective:

1. There already exists a crate with the same name. In that case the rest of the workspace crate creation process will fail and clean up the mess, stating that a package with the given name exists. The user will be able to use the opt-in feature of passing `--name` on the command line to fix that up manually
2. Something else with the name inferring doesn't work out. I'm not even sure if that can be the case anymore, but `file_name` on paths only returns an optional `&str`. In case of a failure there we still use the old behavior of specifying the package name via the command line prompt that was in place beforehand

In any other case the user will just experience less friction which will hopefully improve the user experience.

## Examples:

```
cargo ws create abc
```
the package name is `abc`

---

```
cargo ws create subfolder/def
```
the package name is `def`

---

```
cargo ws create subfolder/abc
```
the package name is also `abc`, hence the user has to pass `--name=SOMETHING` where `SOMETHING` is neither `abc` or `def`

2023-12-22 17:35 UTC, pksunkara requested changes
Instead of doing it like this, why don't you set the name input default? Looks better to me from UX perspective.

2023-12-22 19:20 UTC, RobWalt commented
Ah yeah that also makes sense. My main motivation for this was:

- I want to prevent the need to press enter one extra time
- I just want to mirror `cargo new` as closely as possible

We can meet in the middle with your idea though if you like it to be that way 👍

2023-12-23 03:22 UTC, pksunkara commented
Yeah, I think it's a good middle especially when the user is not satisfied with the derived name and they  don't need to run another command afterwards.

2023-12-26 17:44 UTC, RobWalt commented
I added the changes from the compromise :+1:

2023-12-27 08:58 UTC, pksunkara reviewed
You seemed to add nix files again

2023-12-27 12:06 UTC, RobWalt commented
My bad, sorry, they are removed now :+1:

2023-12-27 13:06 UTC, pksunkara approved these changes

2023-12-27 14:21 UTC, merged